{{- template "common.deployment" (list . "nginx-rtmp.deployment") -}}
{{- define "nginx-rtmp.deployment" -}}

spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "nginx-rtmp.container") }}

{{- end -}}


{{- define "nginx-rtmp.container" -}}

ports:
- name: tcp
  containerPort: 1935
  hostPort: 1935
  protocol: TCP
livenessProbe:
  tcpSocket:
    port: 1935
readinessProbe:
  tcpSocket:
    port: 1935

{{- end -}}
