apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm-chart.fullname" . }}-kube-state-metrics
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "helm-chart.fullname" . }}-kube-state-metrics
          servicePort: 8080
        {{- if .Values.path }}
        path: {{ .Values.path }}
        {{- end }}
