debug: true
initDownstreams: true
entries:
  - name: verdun-prometheus
    upstream:
      type: docker
      repo: prom/prometheus
    downstream:
      type: yaml
      url: https://raw.githubusercontent.com/Croissong/verdun/master/k8s/values/images.yml
      path: 'prometheus.tag'

    hooks:
      - type: git
        repo: git@github.com:Croissong/verdun.git
        change:
          command: |
            yq w k8s/values/images.yml 'prometheus.tag' {{.NewVersion}} | sponge k8s/values/images.yml
        commit:
          msgTemplate: 'Bump prometheus -> {{.NewVersion}}'
          branch: master
          push: true
          authorEmail: releasewatcher@patrician.cloud
          authorName:  ReleaseWatcher Bot


  - name: verdun-riot
    upstream:
      type: docker
      repo: vectorim/riot-web
    downstream:
      type: yaml
      url: https://raw.githubusercontent.com/Croissong/verdun/master/k8s/values/images.yml
      path: 'matrix.riot.tag'

    hooks:
      - type: git
        repo: git@github.com:Croissong/verdun.git
        change:
          command: |
            yq w k8s/values/images.yml 'matrix.riot.tag' {{.NewVersion}} | sponge k8s/values/images.yml
        commit:
          msgTemplate: 'Bump riot -> {{.NewVersion}}'
          branch: master
          push: false
          authorEmail: releasewatcher@patrician.cloud
          authorName:  ReleaseWatcher Bot

  - name: verdun-traefik
    upstream:
      type: docker
      repo: traefik
    downstream:
      type: yaml
      url: https://raw.githubusercontent.com/Croissong/verdun/master/k8s/values/images.yml
      path: 'traefik.tag'

    hooks:
      - type: git
        repo: git@github.com:Croissong/verdun.git
        change:
          command: |
            yq w k8s/values/images.yml 'traefik.tag' {{.NewVersion}} | sponge k8s/values/images.yml
        commit:
          msgTemplate: 'Bump traefik -> {{.NewVersion}}'
          branch: master
          push: true
          authorEmail: releasewatcher@patrician.cloud
          authorName:  ReleaseWatcher Bot

  - name: matrix-synapse-s3-storage
    upstream:
      type: docker
      repo: matrixdotorg/synapse
    downstream:
      type: regex
      url: https://raw.githubusercontent.com/Croissong/matrix-synapse-s3-storage/master/Dockerfile
      regex: '.*synapse:(.*).*'
    hooks:
      - type: git
        repo: git@github.com:Croissong/matrix-synapse-s3-storage.git
        change:
          command: |
            sed -i s/{{.OldVersion}}/{{.NewVersion}}/ Dockerfile
        commit:
          msgTemplate: 'Bump -> {{.NewVersion}}'
          branch: master
          push: true
          authorEmail: releasewatcher@patrician.cloud
          authorName:  ReleaseWatcher Bot
          tag: '{{.NewVersion}}'


  - name: verdun-synapse
    upstream:
      type: docker
      repo: croissong/matrix-synapse-s3-storage
    downstream:
      type: yaml
      url: https://raw.githubusercontent.com/Croissong/verdun/master/k8s/values/images.yml
      path: 'matrix.synapse.tag'

    hooks:
      - type: git
        repo: git@github.com:Croissong/verdun.git
        change:
          command: |
            yq w k8s/values/images.yml 'matrix.synapse.tag' {{.NewVersion}} | sponge k8s/values/images.yml
        commit:
          msgTemplate: 'Bump synapse -> {{.NewVersion}}'
          branch: master
          push: true
          authorEmail: releasewatcher@patrician.cloud
          authorName:  ReleaseWatcher Bot
