kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "traefik.fullname" . }}-acme
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.acme.persistence.size | quote }}
