apiVersion: v1
kind: Secret
metadata:
  name: {{ template "traefik.fullname" . }}-acme
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  DO_AUTH_TOKEN: {{ .Values.acme.provider.digitalocean.DOAuthToken | b64enc | quote }}
