apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: :{{ .Values.ports.web.port }}
      websecure:
        address: :{{ .Values.ports.websecure.port }}
      traefik:
        address: :{{ .Values.ports.traefik.port }}
    providers:
      kubernetesCRD: {}
    api:
      insecure: true
      dashboard: true
      debug: false
    metrics:
      prometheus: {}
    global:
      sendAnonymousUsage: true
    ping: true
    log:
      level: {{ .Values.log.level }}
    certificatesResolvers:
      default:
        acme:
          email: {{ .Values.acme.email }}
          storage: /acme/acme.json
          dnsChallenge:
            provider: {{ .Values.acme.provider.name }}
