{{- $serviceNameDefault :=  printf "%s-%s" .Release.Name .Release.Name -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
{{ template "common.metadata" . }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: default
    options:
      name: default
      namespace: traefik
{{- if .Values.domains }}
    domains:
{{ toYaml .Values.domains | indent 6 }}
{{- end }}
  routes:
  - match: Host(`{{ required "host is required" .Values.host }}`)
    {{- if .Values.path }} && PathPrefix(`{{ .Values.path }}`) {{- end }}
    kind: Rule
    services:
    - name: {{ .Values.serviceName | default $serviceNameDefault }}
      port: {{ required "servicePort is required" .Values.servicePort }}
    middlewares:
    - name: sec-headers
      namespace: traefik
    {{- if and .Values.path .Values.stripPath }}
    - name: {{ template "common.fullname" . }}-stripprefix
    {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "common.fullname" . }}-https-redirect
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.host }}`)
    {{- if .Values.path }} && PathPrefix(`{{ .Values.path }}`) {{- end }}
    kind: Rule
    services:
    - name: {{ .Values.serviceName | default $serviceNameDefault }}
      port: {{ required "servicePort is required" .Values.servicePort }}
    middlewares:
    - name: redirect-https
      namespace: traefik


{{- if and .Values.path .Values.stripPath }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "common.fullname" . }}-stripprefix
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.path }}
{{- end }}
