{{- template "common.configmap" (list . "mychart.configmap") -}}
{{- define "mychart.configmap" -}}

data:
  # https://github.com/vector-im/riot-web/blob/develop/config.sample.json
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}

{{- end -}}
