{{- template "common.deployment" (list . "mychart.deployment") -}}
{{- define "mychart.deployment" -}}

spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - {{ template "common.container" (list . "mychart.deployment.container") }}
      volumes:
        - name: "riot-config"
          configMap:
            name: {{ include "common.fullname" . }}

{{- end -}}

{{- define "mychart.deployment.container" -}}

ports:
- name: riot
  containerPort: 80
volumeMounts:
- name: "riot-config"
  mountPath: /app/config.json
  subPath: config.json

livenessProbe:
  httpGet:
    path: /
    port: riot
readinessProbe:
  httpGet:
    path: /
    port: riot

{{- end -}}
