{{- template "common.service" (list . "matrix-riot.mail.service") -}}
{{- define "matrix-riot.mail.service" -}}

spec:
  ports:
  - name: riot
    protocol: TCP
    port: 80
    targetPort: riot

{{- end -}}
