{{- if eq .Values.ingressMonitorController.mount "configMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}
{{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}
{{- end }}
  annotations:
{{- if .Values.ingressMonitorController.config.annotations }}
{{ toYaml .Values.ingressMonitorController.config.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "ingressmonitorcontroller.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.ingressMonitorController.config.labels }}
{{ toYaml .Values.ingressMonitorController.config.labels | indent 4 }}
{{- end }}
{{- if .Values.ingressMonitorController.matchLabels }}
{{ toYaml .Values.ingressMonitorController.matchLabels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.ingressMonitorController.data | indent 2 }}
{{- end }}
