apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "monitor.stakater.com/enabled": "true"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "helm-chart.fullname" . }}
          servicePort: 80
