apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "monitor.stakater.com/enabled": "true"
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: default
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name:  {{ include "helm-chart.fullname" . }}
      port: 80
