nginx:
  host: verdun.patrician.gold
  serverBlock: |
    server {
      listen 0.0.0.0:8080;

      location ~ ^/index.html {
        root   /static/frontend;
      }

      location ~ \..* {
        add_header Cache-Control "public, max-age=31536000, immutable";
        root   /static/frontend;
      }

      location / {
        rewrite ^.*$ /index.html;
      }
    }
