nginx:
  host: verdun.patrician.cloud
  serverBlock: |
    server {
      listen 0.0.0.0:8080;

      location ~ \..* {
        root   /static/frontend;
      }

      location / {
        rewrite ^.*$ /index.html;
      }
    }
