api-ingress:
  host: verdun.patrician.cloud
  path: /api
  servicePort: 80
  stripPath: true

nginx:
  ingress:
    host: verdun.patrician.cloud
    serviceName: verdun-scribble-nginx
  serverBlock: |
    server {
      listen 0.0.0.0:8080;

      location ~ \..* {
        root   /static/frontend;
      }

      location / {
        rewrite ^.*$ /index.html;
      }
    }
