defaultRules:
  create: false

alertmanager:
  serviceMonitor:
    selfMonitor: false
  config:
    receivers:
    - name: 'null'

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [namespace]
        regex: kube-system
        action: drop


## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  serviceMonitor:
    selfMonitor: false
  kubeletService:
    enabled: false

  image:
    tag: v0.31.1
    pullPolicy: Always

  configmapReloadImage:
    tag: v0.0.1

  prometheusConfigReloaderImage:
    tag: v0.31.1

  hyperkubeImage:
    tag: v1.12.1
    pullPolicy: Always

prometheus:
  enabled: true
  serviceMonitor:
    selfMonitor: false
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 1d
    image:
      tag: v2.10.0
  ingress:
    enabled: true
    hosts:
      - prometheus.patrician.gold
