defaultRules:
  create: false

alertmanager:
  serviceMonitor:
    selfMonitor: false
  config:
    receivers:
    - name: 'null'

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [namespace]
        regex: kube-system
        action: drop


## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  serviceMonitor:
    selfMonitor: false
  kubeletService:
    enabled: false

  image:
    pullPolicy: Always

prometheus:
  enabled: true
  serviceMonitor:
    selfMonitor: false
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 1d
  ingress:
    enabled: true
    hosts:
      - prometheus.patrician.cloud
