{{- template "common.configmap" (list . "murmur.configmap") -}}
{{- define "murmur.configmap" -}}

data:
  murmur.ini: |-
{{ include "murmur.ini" . | indent 4 }}
  ping.py: |-
{{ include "ping.py" . | indent 4 }}
  
{{- end -}}
