{{- template "common.deployment" (list . "murmur.deployment") -}}
{{- define "murmur.deployment" -}}

spec:
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:

        - name: copy-config
          image: supinf/envsubst
          command: ['/bin/sh']
          args:
            - '-c'
            - 'cat /tmp/murmur.ini | envsubst > /opt/murmur/config/murmur.ini'
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: murmur.{{ include "common.name" . }}-postgres.credentials
                key: password
          volumeMounts:
            - name: murmur-config
              mountPath: /tmp/murmur.ini
              subPath: murmur.ini
            - name: config-dir
              mountPath: /opt/murmur/config

        - name: {{ .Chart.Name }}-readycheck
          image: "postgres:11"
          imagePullPolicy: Always
          command: ['sh', '-c',
                    'until pg_isready -h {{ include "common.name" . }}-postgres -p 5432;
                    do echo waiting for database; sleep 2; done;']
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: murmur.{{ include "common.name" . }}-postgres.credentials
                key: password

      containers:
      - {{ template "common.container" (list . "murmur.deployment.container") }}
      volumes:
        - name: murmur-config
          configMap:
            name: {{ template "common.fullname" . }}
        - name: ssl-config
          secret:
            secretName: {{ template "common.fullname" . }}
        - name: config-dir
          emptyDir: {}

{{- end -}}

{{- define "murmur.deployment.container" -}}

ports:
- name: tcp
  containerPort: 64738
  hostPort: 64738
  protocol: TCP
- name: udp
  containerPort: 64738
  hostPort: 64738
  protocol: UDP
volumeMounts:
- name: config-dir
  mountPath: /etc/murmur/murmur.ini
  subPath: murmur.ini
- name: murmur-config
  mountPath: /etc/murmur/ping.py
  subPath: ping.py
- name: ssl-config
  mountPath: /etc/murmur/ssl
livenessProbe:
   exec:
     command: ['python2.7', '/etc/murmur/ping.py', 'localhost', '64738']
readinessProbe:
  exec:
     command: ['python2.7', '/etc/murmur/ping.py', 'localhost', '64738']
{{- end -}}
