{{- template "common.configmap" (list . "authproxy.configmap") -}}
{{- define "authproxy.configmap" -}}
data:
  oauth2_proxy.cfg: |-
    provider = "oidc"
    oidc_issuer_url = "https://dex.patrician.cloud"

    skip_provider_button = true
    http_address = "0.0.0.0:3000"
    email_domains = [
         "*"
    ]
    cookie_refresh = "1h"

    upstreams = [
      "http://{{ required "upstream is required" .Values.upstream }}"
    ]
    request_logging = false
    standard_logging = false
    auth_logging = false
{{- end -}}
