{{- template "common.deployment" (list . "authproxy.deployment") -}}
{{- define "authproxy.deployment" -}}

spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yml") . | sha256sum }}
    spec:
      containers:
      - {{ template "common.container" (list . "authproxy.deployment.container") }}
      volumes:
      - name: auth-proxy
        configMap:
          name: {{ template "common.fullname" . }}

{{- end -}}

{{- define "authproxy.deployment.container" -}}

args:
  - --config=/opt/oauth2_proxy.cfg
envFrom:
  - secretRef:
      name: {{ template "common.fullname" . }}
volumeMounts:
  - name: auth-proxy
    mountPath: /opt/oauth2_proxy.cfg
    subPath: oauth2_proxy.cfg
ports:
  - name: auth-proxy
    containerPort: 3000

{{- end -}}
