{{- template "common.secret" (list . "mychart.secret") -}}
{{- define "mychart.secret" -}}

data:
  OAUTH2_PROXY_CLIENT_ID: {{ required "clientId is required" .Values.clientId | b64enc | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ required "clientSecret is required" .Values.clientSecret | b64enc | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ required "cookieSecret is required" .Values.cookieSecret | b64enc | quote }}
  OAUTH2_PROXY_GITHUB_ORG: {{ required "githubOrg is required" .Values.githubOrg | b64enc | quote }}

{{- end -}}
