apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "auth-proxy.fullname" . }}
  labels:
    app: {{ template "auth-proxy.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  oauth2_proxy.cfg: |
    provider = "oidc"
    oidc_issuer_url = "https://dex.patrician.cloud"

    skip_provider_button = true
    http_address = "0.0.0.0:3000"
    email_domains = [
         "*"
    ]
    cookie_refresh = "1h"

    upstreams = [
    "http://{{ .Values.upstream }}"
    ]
    request_logging = false
    standard_logging = false
    auth_logging = false
