{{- template "common.deployment" (list . "hefeteig-app.deployment") -}}
{{- define "hefeteig-app.deployment" -}}

spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "hefeteig-app.deployment.container") }}

{{- end -}}

{{- define "hefeteig-app.deployment.container" -}}

ports:
- name: http
  containerPort: 80
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


{{- end -}}
