version: 2.1
workflows:
   version: 2
   build:
     jobs:
       - circle-compare-url/reconstruct
       - run_ci:
           requires:
             - circle-compare-url/reconstruct
       - run_k8s_manual:
           type: approval
       - run_frontend_manual:
           type: approval

orbs:
  circle-compare-url: iynere/compare-url@1.0.2

jobs:
  run_ci:
    docker:
      - image: croissong/verdun-ci:latest
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "40:f3:ca:86:a6:53:99:ce:21:16:58:f9:25:8c:ef:da"
      - checkout
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: run ci
          command: python3 .circleci/circle.py
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./frontend/node_modules
  run_k8s_manual:
    docker:
      - image: croissong/verdun-ci:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: run ci
          command: python3 .circleci/circle.py --k8s

  run_frontend_manual:
    docker:
      - image: croissong/verdun-ci:latest
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "40:f3:ca:86:a6:53:99:ce:21:16:58:f9:25:8c:ef:da"
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: run ci
          command: python3 .circleci/circle.py --frontend
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./frontend/node_modules
