version: 2
jobs:
  build:
    docker:
      - image: quay.io/roboll/helmfile:v0.59.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - packages-v1
      - run: apk add make curl
      - save_cache:
          key: packages-v1
          paths:
            - "/var/cache/apk"
      - run:
          command: |
            make get-kubeconf do_token=$DO_TOKEN_GET_KUBECONF cluster_id=$DO_K8S_CLUSTER_ID
          working_directory: ~/project/k8s
      - run:
          command: make status kubectx=$K8S_CLUSTER_CONTEXT
          working_directory: ~/project/k8s
