version: 2
workflows:
   version: 2
   build:
     jobs:
       - deploy_k8s
jobs:
  deploy_k8s:
    docker:
      - image: quay.io/roboll/helmfile:v0.64.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - packages-v1
      - run: apk add make curl gnupg python3
      - save_cache:
          key: packages-v1
          paths:
            - "/var/cache/apk"
      - run:
          command: |
            k8s_changed=`python3 .circleci/changed-since-last-commit.py k8s`
            if [[ $k8s_changed == "True" ]]; then
              python3 .circleci/k8s.py
            fi
