version: 2.1
workflows:
   version: 2
   build:
     jobs:
       - circle-compare-url/reconstruct
       - build_frontend:
           requires:
            - circle-compare-url/reconstruct
       # - package_frontend
       - deploy_k8s:
           requires:
            - circle-compare-url/reconstruct

orbs:
  circle-compare-url: iynere/compare-url@1.0.2

jobs:
  build_frontend:
    docker:
      - image: alpine/git
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "40:f3:ca:86:a6:53:99:ce:21:16:58:f9:25:8c:ef:da"
      - checkout
      - restore_cache:
          keys:
            - packages-v1
      - run: apk add python3
      - save_cache:
          key: packages-v1
          paths:
            - "/var/cache/apk"
      - attach_workspace:
          at: workspace
      - run:
          command: |
            if python3 .circleci/changed-since-last-commit.py frontend; then
              python3 .circleci/frontend.py
            fi
  deploy_k8s:
    docker:
      - image: quay.io/roboll/helmfile:v0.64.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - packages-v1
      - run: apk add make curl gnupg python3
      - save_cache:
          key: packages-v1
          paths:
            - "/var/cache/apk"
      - attach_workspace:
          at: workspace
      - run:
          command: |
            if python3 .circleci/changed-since-last-commit.py k8s; then
              python3 .circleci/k8s.py
            fi
