version: 2
jobs:
  build:
    docker:
      - image: everpeace/kubectl:latest
    steps:
      - restore_cache:
          keys:
            - packages-v1
      - checkout
      - run: apk add gomplate curl
      - save_cache:
          key: packages-v1
          paths:
            - "/var/cache/apk"
      - run: >
          curl -s -H "Authorization: Bearer $DO_TOKEN_GET_KUBECONF" "https://api.digitalocean.com/v2/kubernetes/clusters/$DO_K8S_CLUSTER_ID/kubeconfig" > kubeconfig.yaml
      - run: kubectl --kubeconfig="$PWD/kubeconfig.yaml" get ns
