{{- template "common.configmap" (list . "matrix-synapse.configmap") -}}
{{- define "matrix-synapse.configmap" -}}

data:
  # https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml
  homeserver.yaml: |-
{{ include "homeserver.yaml" . | indent 4 }}
    
  log.config: |-
{{ include "log.config" . | indent 4 }}

{{- end -}}
