{{- template "common.configmap" (list . "matrix-synapse.configmap") -}}
{{- define "matrix-synapse.configmap" -}}

data:
  homeserver.yaml: |-
{{ tpl (.Files.Get "files/homeserver.yaml") . | indent 4 }}

  log.config: |-
{{ tpl (.Files.Get "files/log.config") . | indent 4 }}

{{- end -}}
