{{- template "common.deployment" (list . "matrix-synapse.deployment") -}}
{{- define "matrix-synapse.deployment" -}}

spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - {{ template "common.container" (list . "matrix-synapse.deployment.container") }}
      initContainers:
        - name: config-envsubst
          image: supinf/envsubst
          command: ['/bin/sh']
          args:
            - '-c'
            - 'cat /conf/homeserver.yaml | envsubst > /envsubst-conf/homeserver.yaml'
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: synapse.{{ template "common.name" . }}-postgres.credentials
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: synapse.{{ template "common.name" . }}-postgres.credentials
                key: password
          volumeMounts:
            - name: "synapse-config"
              mountPath: "/conf/homeserver.yaml"
              subPath: homeserver.yaml
            - name: envsubst-conf
              mountPath: "/envsubst-conf"

        - name: {{ .Chart.Name }}-readycheck
          image: "postgres:11"
          imagePullPolicy: Always
          command: ['sh', '-c',
                    'until pg_isready -h {{ include "common.name" . }}-postgres -p 5432;
                    do echo waiting for database; sleep 2; done;']
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: synapse.{{ include "common.name" . }}-postgres.credentials
                key: password

      volumes:
        - name: "synapse-config"
          configMap:
            name: {{ template "common.fullname" . }}
        - name: "signing-key"
          secret:
            secretName: {{ template "common.fullname" . }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ template "common.fullname" . }}
        - name: envsubst-conf
          emptyDir: {}
        - name: data
          emptyDir: {}

{{- end -}}

{{- define "matrix-synapse.deployment.container" -}}

ports:
  - name: http
    containerPort: 8008
  - name: metrics
    containerPort: 9000
env:
  - name: SYNAPSE_CONFIG_PATH
    value: "/envsubst-conf/homeserver.yaml"
envFrom:
  - secretRef:
      name:  {{ template "common.fullname" . }}
volumeMounts:
  - name: envsubst-conf
    mountPath: "/envsubst-conf"
  - name: synapse-config
    mountPath: "/conf/log.config"
    subPath: log.config
  - name: signing-key
    mountPath: "/data/{{ .Values.host }}.signing.key"
    subPath: signing.key
  - name: uploads
    mountPath: "/data/uploads"
  - name: data
    mountPath: "/data"
livenessProbe:
  httpGet:
    path: /_matrix/static/
    port: http
readinessProbe:
  httpGet:
    path: /_matrix/static/
    port: http

{{- end -}}
