{{- template "common.secret" (list . "matrix-synapse.secret") -}}
{{- define "matrix-synapse.secret" -}}

data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3AccessId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3SecretKey | b64enc | quote }}
  signing.key: {{ .Values.signingKeyB64 | quote }}

{{- end -}}
