{{- template "common.service" (list . "matrix-synapse.mail.service") -}}
{{- define "matrix-synapse.mail.service" -}}

spec:
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: http
    - name: metrics
      port: 9000
      targetPort: metrics

{{- end -}}
