apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
{{ template "common.metadata" . }}
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: /
  jobLabel: app
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
      release: {{ .Release.Name }}
