apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-auth
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.password | b64enc | quote }}
