apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ required "postgresVersion is required" .Values.postgresVersion | quote }}
  storageType: Durable
  databaseSecret:
    secretName: {{ include "helm-chart.fullname" . }}-auth
  storage:
    storageClassName: "do-block-storage"
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storageSize}}
  terminationPolicy: Pause
  archiver:
    storage:
      storageSecretName: {{ include "helm-chart.fullname" . }}-s3-secret
      s3:
        endpoint:  https://verdun.fra1.digitaloceanspaces.com
        bucket: backup
  init:
    postgresWAL:
      storageSecretName: {{ include "helm-chart.fullname" . }}-s3-secret
      s3:
        endpoint:  https://fra1.digitaloceanspaces.com
        bucket: verdun
        prefix: 'backup/kubedb/matrix/matrix-synapse-postgres/archive'
