context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: false
  tillerless: true
  atomic: true
  wait: true
  recreatePods: false

environments:
  default:
    values:
      - values/images.yml
    secrets:
      - values/secrets.yaml

releases:

# https://www.digitalocean.com/community/questions/hi-after-some-update-of-the-kubernetes-ltd-access-to-a-container-through-hostport-was-broken-i-assume-this-is-related-to-cilium-anyone-known-how-to-fix-that
- name: cilium-portmap
  namespace: kube-system
  chart: ./my-charts/cilium-portmap/

- name: traefik-auth-proxy
  namespace: traefik
  chart: ./my-charts/auth-proxy/
  values:
    - values/auth-proxy.yml.gotmpl
    - domain: traefik.patrician.gold
      upstream: traefik-dashboard:80

- name: traefik
  namespace: traefik
  chart: ./my-charts/traefik/
  recreatePods: true
  values:
    - values/traefik.yml.gotmpl

- name: matrix-synapse
  namespace: comm-tools
  chart: ./my-charts/matrix-synapse/
  verify: false
  values:
    - imageTag: v0.99.5.1
    - matrix-synapse-values.yml.gotmpl
    - common-values.yml.gotmpl

- name: matrix-riot
  namespace: comm-tools
  chart: ./my-charts/matrix-riot/
  verify: false
  values:
    - imageTag: v1.1.2

- name: mumble
  namespace: comm-tools
  chart: ./my-charts/mumble/
  recreatePods: true
  verify: false
  values:
    - imageTag: rc
    - murmur-values.yml.gotmpl
    - common-values.yml.gotmpl

- name: nginx-rtmp
  namespace: comm-tools
  chart: ./my-charts/nginx-rtmp/
  verify: false
  recreatePods: true
  values:
    - imageTag: latest

- name: kube-state-metrics
  namespace: verdun
  chart: ./my-charts/kube-state-metrics/
  values:
    - image.tag: v1.6.0
    - kube-state-metrics-values.yml

- name: verdun-frontend
  namespace: verdun
  chart: ./my-charts/verdun-frontend/
  values:
    - imageTag: 2cb6121
    - common-values.yml.gotmpl
