context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: tiller
  tillerless: true
  atomic: true
  wait: true
  recreatePods: false

environments:
  default:
    values:
      - helm_vars/values.yaml
    secrets:
      - helm_vars/secrets.yaml

releases:

- name: traefik-auth-proxy-conf
  namespace: traefik
  chart: ./my-charts/auth-proxy-conf/
  version: ~0.0.1
  values:
    - common-values.yml.gotmpl
    - authProxy:
        domain: traefik.patrician.gold
        upstream: 127.0.0.1:8080

- name: traefik
  namespace: traefik
  chart: ./my-charts/traefik/
  version: ~1.68.1
  recreatePods: true
  values:
    - imageTag: 1.7.10-alpine
    - ./traefik-values.yml.gotmpl
    - common-values.yml.gotmpl

- name: matrix-synapse
  namespace: comm-tools
  chart: ./my-charts/matrix-synapse/
  verify: false
  values:
    - imageTag: v0.99.5.1
    - matrix-synapse-values.yml.gotmpl
    - common-values.yml.gotmpl

- name: matrix-riot
  namespace: comm-tools
  chart: ./my-charts/matrix-riot/
  verify: false
  values:
    - imageTag: v1.1.2

- name: mumble
  namespace: comm-tools
  chart: ./my-charts/mumble/
  recreatePods: true
  verify: false
  values:
    - imageTag: rc
    - murmur-values.yml.gotmpl
    - common-values.yml.gotmpl

- name: nginx-rtmp
  namespace: comm-tools
  chart: ./my-charts/nginx-rtmp/
  verify: false
  recreatePods: true
  values:
    - imageTag: latest

- name: kube-state-metrics
  namespace: verdun
  chart: ./my-charts/kube-state-metrics/
  values:
    - image.tag: v1.6.0
    - kube-state-metrics-values.yml

- name: verdun-frontend
  namespace: verdun
  chart: ./my-charts/verdun-frontend/
  values:
    - imageTag: 2cb6121
    - common-values.yml.gotmpl
