context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: tiller
  wait: true
  recreatePods: false

environments:
  default:
    secrets:
      - helm_vars/secrets.yaml

releases:
- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.66.0
  values:
    - ./traefik-values.yml
- name: matrix-synapse
  namespace: comm-tools
  chart: ./my-charts/matrix-synapse/
  verify: false
  values:
    - matrix-synapse-values.yml
- name: matrix-riot
  namespace: comm-tools
  chart: ./my-charts/matrix-riot/
  verify: false
- name: mumble
  namespace: comm-tools
  chart: ./my-charts/mumble/
  verify: false
