context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: kube-system  #dedicated default key for tiller-namespace
  wait: true
  recreatePods: false

environments:
  default:
    secrets:
      - helm_vars/secrets.yaml

releases:
- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.52.6
  values:
    - "./traefik-values.yaml.gotmpl"
- name: matrix-synapse
  namespace: comm-tools
  chart: ./comm-tools/matrix-synapse/
  verify: false
  values:
    - matrix-synapse-values.yaml.gotmpl
- name: matrix-riot
  namespace: comm-tools
  chart: ./comm-tools/matrix-riot/
  verify: false
