context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: tiller
  tillerless: true
  atomic: true
  wait: true
  recreatePods: false

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: appscode
  url: https://charts.appscode.com/stable/

environments:
  default:
    values:
      - values/images.yml
    secrets:
      - values/secrets.yaml

releases:

- name: prometheus
  namespace: prometheus
  chart: ./my-charts/prometheus/
  version: 5.15.0
  values:
    - values/my-prometheus.yml.gotmpl
    - prometheus-operator:
{{ readFile "values/prometheus-operator.yml" | indent 8 }}
        kube-state-metrics:
{{ readFile "values/kube-state-metrics.yml" | indent 10 }}

- name: kubedb-operator
  namespace: kubedb
  chart: appscode/kubedb
  version: 0.12.0
  wait: false
  atomic: false

- name: kubedb-catalog
  namespace: kubedb
  chart: appscode/kubedb-catalog
  version: 0.12.0
  wait: false
  atomic: false

- name: stash-operator
  namespace: stash
  chart: appscode/stash
  version: 0.8.3
  wait: false
  atomic: false
  values:
    - values/common.yml.gotmpl

- name: traefik
  namespace: traefik
  chart: ./my-charts/traefik/
  values:
    - values/traefik.yml.gotmpl
    - values/common.yml.gotmpl
    - auth-proxy:
        domain: traefik.patrician.gold
        upstream: traefik-dashboard:80

- name: matrix-synapse
  namespace: matrix
  chart: ./my-charts/matrix-synapse/
  verify: false
  values:
    - values/synapse.yml.gotmpl
    - values/common.yml.gotmpl

- name: matrix-riot
  namespace: matrix
  chart: ./my-charts/matrix-riot/
  verify: false
  values:
    - values/riot.yml.gotmpl

- name: murmur
  namespace: murmur
  chart: ./my-charts/murmur/
  recreatePods: true
  verify: false
  values:
    - values/murmur.yml.gotmpl
    - values/common.yml.gotmpl

- name: nginx-rtmp
  namespace: misc
  chart: ./my-charts/nginx-rtmp/
  verify: false
  recreatePods: true
  values:
    - values/nginx-rtmp.yml.gotmpl

- name: verdun-frontend
  namespace: verdun
  chart: ./my-charts/verdun-frontend/
  values:
    - values/common.yml.gotmpl
    - values/verdun.yml.gotmpl

- name: verdun-api
  namespace: verdun
  chart: ./my-charts/verdun-api/
  values:
    - values/verdun-api.yml.gotmpl

- name: hefeteig-app
  namespace: hefeteig
  chart: ./my-charts/hefeteig-app/
  values:
    - values/common.yml.gotmpl

- name: ingress-monitor-controller
  namespace: verdun
  chart: ./my-charts/ingressmonitorcontroller/
  values:
    - values/ingressmonitorcontroller.yml.gotmpl

- name: concourse
  namespace: concourse
  chart: stable/concourse
  values:
    - persistence.enabled: false
    - postgresql.persistence.enabled: false
    - web:
        ingress:
          enabled: true
          hosts:
          - concourse.patrician.gold
    - secrets:
        githubClientId: 36e8d7181c9014981d0b
        githubClientSecret: 34363aa0fde9e563bd3e49d39915db621316b0f7
    - concourse:
        web:
          externalUrl: https://concourse.patrician.gold
          localAuth:
            enabled: false
          auth:
            github:
              enabled: true
            mainTeam:
              github:
                org: {{ .Environment.Values.authProxy.githubOrg }}
        worker:
          baggageclaim:
            driver: btrfs
