helmDefaults:
  kubeContext: do-fra1-verdun
  atomic: true
  recreatePods: false
  timeout: 180

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: appscode
  url: https://charts.appscode.com/stable/

environments:
  default:
    values:
    - values/images.yml
    secrets:
    - values/secrets.yaml

releases:

- name: prometheus
  namespace: prometheus
  chart: stable/prometheus-operator
  version: 8.5.0
  values:
  - values/prometheus.yml.gotmpl

- name: prometheus-ingress
  namespace: prometheus
  chart: ./charts/ingress
  values:
  - host: prometheus.patrician.cloud
    serviceName: prometheus-prometheus-oper-prometheus
    servicePort: 9090
  needs:
  - prometheus/prometheus
  - traefik/traefik-middlewares

- name: traefik
  namespace: traefik
  chart: ./charts/traefik
  values:
  - values/traefik.yml.gotmpl
  needs:
  - prometheus/prometheus

- name: traefik-middlewares
  namespace: traefik
  chart: ./charts/traefik-middlewares
  needs:
  - traefik/traefik

# - name: traefik-authproxy
#   namespace: traefik
#   chart: ./charts/authproxy
#   values:
#     - values/authproxy.yml.gotmpl
#     - upstream: traefik-dashboard:80
#       ingress:
#         host: traefik.patrician.cloud
#         domains:
#           - main: "patrician.cloud"
#           - sans:
#               - "*.patrician.cloud"
#   needs:
#     - traefik/traefik
#     - traefik/traefik-middlewares
#     - dex/dex-ingress

- name: matrix-synapse
  namespace: matrix
  chart: ./charts/matrix-synapse/
  values:
  - values/synapse.yml.gotmpl
  - values/common.yml.gotmpl
  needs:
  - traefik/traefik-middlewares
  - postgres-operator/postgres-operator
  - prometheus/prometheus

- name: matrix-riot
  namespace: matrix
  chart: ./charts/matrix-riot/
  values:
  - values/riot.yml.gotmpl
  needs:
  - matrix/matrix-synapse
  - traefik/traefik-middlewares

- name: murmur
  namespace: murmur
  chart: ./charts/murmur/
  values:
  - values/murmur.yml.gotmpl
  - values/common.yml.gotmpl

- name: nginx-rtmp
  namespace: misc
  chart: ./charts/nginx-rtmp/
  recreatePods: true
  values:
  - values/nginx-rtmp.yml.gotmpl

- name: verdun
  namespace: verdun
  chart: ./charts/verdun
  values:
  - values/common.yml.gotmpl
  - values/verdun.yml.gotmpl
  needs:
  - traefik/traefik-middlewares

- name: hefeteig-app
  namespace: hefeteig
  chart: ./charts/hefeteig-app/
  values:
  - values/hefeteig-app.yml.gotmpl
  needs:
  - traefik/traefik-middlewares

- name: hefeteig-scribble
  namespace: hefeteig
  chart: ./charts/hefeteig-scribble
  values:
  - values/common.yml.gotmpl
  needs:
  - traefik/traefik-middlewares

- name: tekton
  namespace: tekton
  chart: ./charts/tekton
  values:
  - values/common.yml.gotmpl
  - values/tekton.yml

- name: dex
  namespace: dex
  chart: stable/dex
  version: 2.5.0
  values:
  - values/common.yml.gotmpl
  - values/dex.yml.gotmpl

- name: dex-ingress
  namespace: dex
  chart: ./charts/ingress
  values:
  - host: dex.patrician.cloud
    service:
      name: dex
      port: 5556
  needs:
  - dex/dex
  - traefik/traefik
  - traefik/traefik-middlewares

- name: postgres-operator
  namespace: postgres-operator
  chart: ./charts/postgres-operator
  values:
  - charts/postgres-operator/values-crd.yaml
  - values/postgres-operator.yml.gotmpl
