context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  atomic: true
  recreatePods: false

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: appscode
  url: https://charts.appscode.com/stable/

environments:
  default:
    values:
      - values/images.yml
    secrets:
      - values/secrets.yaml

releases:

- name: prometheus
  namespace: prometheus
  chart: ./charts/prometheus
  values:
    - values/prometheus.yml.gotmpl

# - name: kubedb-operator
#   namespace: kubedb
#   chart: appscode/kubedb
#   version: 0.13.0-rc.0
#   wait: false
#   atomic: false

- name: kubedb-catalog
  namespace: kubedb
  chart: appscode/kubedb-catalog
  version: 0.13.0-rc.0
  atomic: false

# - name: stash-operator
#   namespace: stash
#   chart: appscode/stash
#   version: v0.9.0-rc.2
#   atomic: false
#   recreatePods: true
#   values:
#     - values/common.yml.gotmpl
#     - values/stash-operator.yml.gotmpl

- name: traefik
  namespace: traefik
  chart: ./charts/traefik
  values:
    - values/traefik.yml.gotmpl
    - values/common.yml.gotmpl

- name: matrix-synapse
  namespace: matrix
  chart: ./charts/matrix-synapse/
  verify: false
  values:
    - values/synapse.yml.gotmpl
    - values/common.yml.gotmpl
  # needs:
  #   - traefik
  #   - kubedb-operator

- name: matrix-riot
  namespace: matrix
  chart: ./charts/matrix-riot/
  verify: false
  values:
    - values/riot.yml.gotmpl
  # needs:
  #   - traefik

- name: murmur
  namespace: murmur
  chart: ./charts/murmur/
  recreatePods: true
  values:
    - values/murmur.yml.gotmpl
    - values/common.yml.gotmpl

- name: nginx-rtmp
  namespace: misc
  chart: ./charts/nginx-rtmp/
  recreatePods: true
  values:
    - values/nginx-rtmp.yml.gotmpl

- name: verdun-frontend
  namespace: verdun
  chart: ./charts/verdun-frontend/
  values:
    - values/common.yml.gotmpl
    - values/verdun.yml.gotmpl

- name: verdun-api
  namespace: verdun
  chart: ./charts/verdun-api/
  values:
    - values/verdun-api.yml.gotmpl

- name: hefeteig-app
  namespace: hefeteig
  chart: ./charts/hefeteig-app/
  values:
    - values/common.yml.gotmpl

- name: hefeteig-scribble-backend
  namespace: hefeteig
  chart: ./charts/hefeteig-scribble-backend

- name: hefeteig-scribble-app
  namespace: hefeteig
  chart: ./charts/hefeteig-scribble-app
  values:
    - values/common.yml.gotmpl

- name: tekton
  namespace: tekton
  chart: ./charts/tekton
  values:
    - values/tekton.yml
