context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: kube-system  #dedicated default key for tiller-namespace
  verify: true
  wait: true

environments:
  default:
    secrets:
      - helm_vars/secrets.yaml

releases:
- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.52.6
  values:
    - traefik-values.yaml.gotmpl
