context: {{ requiredEnv "KUBECONTEXT" }}

helmDefaults:
  tillerNamespace: tiller
  wait: true
  recreatePods: false

environments:
  default:
    secrets:
      - helm_vars/secrets.yaml

releases:

- name: traefik
  namespace: traefik
  chart: stable/traefik
  version: ~1.68.1
  values:
    - imageTag: 1.7.10-alpine
    - ./traefik-values.yml.gotmpl

- name: matrix-synapse
  namespace: comm-tools
  chart: ./my-charts/matrix-synapse/
  verify: false
  values:
    - imageTag: v0.99.3.2-py3
    - postgresql.image.tag: 11.3-alpine
    - matrix-synapse-values.yml.gotmpl

- name: matrix-riot
  namespace: comm-tools
  chart: ./my-charts/matrix-riot/
  verify: false
  values:
    - imageTag: v1.1.0
- name: mumble
  namespace: comm-tools
  chart: ./my-charts/mumble/
  verify: false
