helmDefaults:
  kubeContext: do-fra1-verdun
  atomic: true
  recreatePods: false

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: appscode
  url: https://charts.appscode.com/stable/

environments:
  default:
    values:
      - values/images.yml
    secrets:
      - values/secrets.yaml

releases:

- name: prometheus
  namespace: prometheus
  chart: stable/prometheus-operator
  version: 8.3.0
  values:
    - values/prometheus.yml.gotmpl

- name: prometheus-ingress
  namespace: prometheus
  chart: ./charts/ingressroute
  values:
    - host: prometheus.patrician.cloud
      service:
        name: prometheus-prometheus-oper-prometheus
        port: 9090
  needs:
    - prometheus/prometheus
    - traefik/traefik
    - traefik/traefik-middlewares

- name: kubedb
  namespace: kubedb
  chart: appscode/kubedb
  version: 0.13.0-rc.0
  wait: false
  atomic: false

- name: kubedb-catalog
  namespace: kubedb
  chart: appscode/kubedb-catalog
  version: 0.13.0-rc.0
  atomic: false

- name: traefik
  namespace: traefik
  chart: ./charts/traefik
  values:
    - values/traefik.yml.gotmpl
  needs:
    - prometheus/prometheus

- name: traefik-middlewares
  namespace: traefik
  chart: ./charts/traefik-middlewares
  needs:
    - traefik/traefik

- name: traefik-authproxy
  namespace: traefik
  chart: ./charts/authproxy
  values:
    - values/authproxy.yml.gotmpl
    - upstream: traefik-dashboard:80
      ingressroute:
        host: traefik.patrician.cloud
        domains:
          - main: "patrician.cloud"
          - sans:
              - "*.patrician.cloud"
  needs:
    - traefik/traefik
    - traefik/traefik-middlewares
    - dex/dex-ingress

- name: matrix-synapse
  namespace: matrix
  chart: ./charts/matrix-synapse/
  values:
    - values/synapse.yml.gotmpl
    - values/common.yml.gotmpl
  needs:
    - traefik
    - kubedb

- name: matrix-riot
  namespace: matrix
  chart: ./charts/matrix-riot/
  verify: false
  values:
    - values/riot.yml.gotmpl
  # needs:
  #   - traefik

- name: murmur
  namespace: murmur
  chart: ./charts/murmur/
  recreatePods: true
  values:
    - values/murmur.yml.gotmpl
    - values/common.yml.gotmpl

- name: nginx-rtmp
  namespace: misc
  chart: ./charts/nginx-rtmp/
  recreatePods: true
  values:
    - values/nginx-rtmp.yml.gotmpl

- name: verdun-frontend
  namespace: verdun
  chart: ./charts/verdun-frontend/
  values:
    - values/common.yml.gotmpl
    - values/verdun.yml.gotmpl

- name: verdun-api
  namespace: verdun
  chart: ./charts/verdun-api/
  values:
    - values/verdun-api.yml.gotmpl

- name: hefeteig-app
  namespace: hefeteig
  chart: ./charts/hefeteig-app/
  values:
    - values/common.yml.gotmpl

- name: hefeteig-scribble-backend
  namespace: hefeteig
  chart: ./charts/hefeteig-scribble-backend

- name: hefeteig-scribble-app
  namespace: hefeteig
  chart: ./charts/hefeteig-scribble-app
  values:
    - values/common.yml.gotmpl

- name: tekton
  namespace: tekton
  chart: ./charts/tekton
  values:
    - values/common.yml.gotmpl
    - values/tekton.yml

- name: dex
  namespace: dex
  chart: stable/dex
  version: 2.5.0
  values:
    - values/common.yml.gotmpl
    - values/dex.yml.gotmpl

- name: dex-ingress
  namespace: dex
  chart: ./charts/ingressroute
  values:
    - host: dex.patrician.cloud
      service:
        name: dex
        port: 5556
  needs:
    - dex/dex
    - traefik/traefik
    - traefik/traefik-middlewares
