nginx:
  host: scribble.hefeteig.io
  serverBlock: |
    server {
      listen 0.0.0.0:8080;

      location ~ \..* {
        root   /static/frontend;
      }

      location / {
        rewrite ^.*$ /index.html;
      }
    }
  fileContainers:
    - name: frontend
      image: registry.gitlab.com/donkebap/hefeteig-scribble-app:latest
      srcPath: /app
      dstPath: frontend
