{{- template "common.configmap" (list . "nginx.configmaps.h5bp-configs") -}}
{{- define "nginx.configmaps.h5bp-configs" -}}

metadata:
  name: {{ include "common.fullname" . }}-h5bp-configs
data:
{{ (.Files.Glob "files/h5bp/**.conf").AsConfig | indent 2 }}

{{- end -}}
