{{- template "common.configmap" (list . "nginx.configmaps.nginx-conf") -}}
{{- define "nginx.configmaps.nginx-conf" -}}

metadata:
  name: {{ include "common.fullname" . }}-nginx
data:
  nginx.conf: |-
{{ .Files.Get "files/nginx.conf" | indent 4 }}

{{- end -}}
