{{- template "common.configmap" (list . "nginx.configmaps.server-block") -}}
{{- define "nginx.configmaps.server-block" -}}

metadata:
  name: {{ include "common.fullname" . }}-server-block
data:
  server-block.conf: |
{{ .Values.serverBlock | indent 4 }}

{{- end -}}
