apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sec-headers
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  headers:
    frameDeny: "true"
    sslRedirect: "true"
    stsSeconds: "31536000"
    stsIncludeSubdomains: "true"
    stsPreload: "true"
    forceSTSHeader: "true"
    contentTypeNosniff: "true"
    browserXssFilter: "true"
    frameDeny: "true"
    referrerPolicy: "no-referrer"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sec-headers-csp
  labels:
    app: {{ template "traefik.name" . }}
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  headers:
    # as custom, otherwise overrides others: https://github.com/containous/traefik/issues/5538
    customResponseHeaders:
      Content-Security-Policy: "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"
