apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 991
      containers:
        - name: {{ .Chart.Name }}
          image: skender/matrix-synapse-s3-storage:{{ .Values.imageTag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: "/envsubst-conf/homeserver.yaml"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-secret
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: envsubst-conf
              mountPath: "/envsubst-conf"
            - name: "synapse-config"
              mountPath: "/conf/log.config"
              subPath: log.config
            - name: data
              mountPath: "/data/uploads"

      initContainers:
        - name: config-envsubst
          image: supinf/envsubst
          command: ['/bin/sh']
          args:
            - '-c'
            - 'cat /conf/homeserver.yaml | envsubst > /envsubst-conf/homeserver.yaml'
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-postgres-auth
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-postgres-auth
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: "synapse-config"
              mountPath: "/conf/homeserver.yaml"
              subPath: homeserver.yaml
            - name: envsubst-conf
              mountPath: "/envsubst-conf"

      volumes:
        - name: "synapse-config"
          configMap:
            name: {{ include "helm-chart.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}-pvc
        - name: envsubst-conf
          emptyDir: {}
