apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 991
      containers:
        - name: {{ .Chart.Name }}
          image: matrixdotorg/synapse:{{ .Values.imageTag }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: "/conf/homeserver.yaml"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}
                  key: postgresql-password
          volumeMounts:
            - name: "synapse-config"
              mountPath: "/conf/homeserver.yaml"
              subPath: homeserver.yaml
            - name: "synapse-config"
              mountPath: "/conf/log.config"
              subPath: log.config
            - name: data
              mountPath: "/data/"
      volumes:
        - name: "synapse-config"
          configMap:
            name: {{ include "helm-chart.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}-pvc
