apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: default
    options:
      name: default
      namespace: traefik
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name:  {{ include "helm-chart.fullname" . }}
      port: 8008
    middlewares:
    - name: sec-headers
      namespace: traefik


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm-chart.fullname" . }}-https-redirect
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name:  {{ include "helm-chart.fullname" . }}
      port: 8008
    middlewares:
    - name: redirect-https
      namespace: traefik

