dependencies:
- name: postgres
  version: "0.1.0"
  repository: "file://../postgres"
- name: ingress
  version: "0.0.1"
  repository: "file://../ingress"
- name: common
  version: 0.0.5
  repository: "file://../common"
