host: matrix.patrician.cloud
ingressroute:
  host: matrix.patrician.cloud
  service:
    port: 8008
    suffix: matrix-synapse
postgres:
  storageSize: 10Gi
  users:
    - synapse
  databases:
    synapse: synapse
  clone: true
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
