host: matrix.patrician.cloud
ingress:
  host: matrix.patrician.cloud
  servicePort: 8008

postgres:
  storageSize: 10Gi
  users:
    - synapse
  databases:
    synapse: synapse
  clone: true
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
