apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-auth
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  user: {{ required "mysql user is required" .Values.user | b64enc | quote }}
  password: {{ required "mysql password is required" .Values.password | b64enc | quote }}
