apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_ACCESS_KEY_ID: {{ required "s3AccessId user is required" .Values.s3AccessId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "s3SecretKey user is required" .Values.s3SecretKey | quote }}
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_ENDPOINT: https://fra1.digitaloceanspaces.com
  WALG_S3_PREFIX: 's3://verdun/spilo/{{ include "helm-chart.fullname" . }}'
  WALG_DISABLE_S3_SSE: "true"
  CLONE_AWS_S3_FORCE_PATH_STYLE: '1'
