{{- template "common.configmap" (list . "postgres.configmap") -}}
{{- define "postgres.configmap" -}}

metadata:
  name: postgres
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_ACCESS_KEY_ID: {{ required "s3AccessId user is required" .Values.s3AccessId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "s3SecretKey user is required" .Values.s3SecretKey | quote }}
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_ENDPOINT: {{ .Values.s3_endpoint }}
  WALG_S3_PREFIX: {{ .Values.s3_prefix }}/{{ include "common.fullname" . }}
  WALG_DISABLE_S3_SSE: "true"
  CLONE_AWS_S3_FORCE_PATH_STYLE: '1'

{{- end -}}
