apiVersion: "acid.zalan.do/v1"
kind: postgresql
{{ include "common.metadata" . }}
spec:
  teamId: {{ .Release.Name }}
  volume:
    size: {{ .Values.storageSize}}
  numberOfInstances: 1
  users:
    # database owner
    {{- range .Values.users }}
    {{ . }}:
    - superuser
    - createdb
    {{- end }}

  # databases: name->owner
  databases:
  {{- range $key, $val := .Values.databases }}
    {{ $key }}: {{ $val }}
  {{- end }}
  postgresql:
    version: "11"
  clone:
    cluster: {{ template "common.fullname" . }}
    timestamp: '3000-01-01T00:00:00+00:00'
    s3_wal_path: {{ .Values.s3_prefix }}/{{ include "common.fullname" . }}
    s3_endpoint: {{ .Values.s3_endpoint }}
    s3_access_key_id: {{ required "s3AccessId user is required" .Values.s3AccessId | quote }}
    s3_secret_access_key: {{ required "s3SecretKey user is required" .Values.s3SecretKey | quote }}
