apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-s3-secret
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ required "s3AccessId user is required" .Values.s3AccessId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "s3SecretKey user is required" .Values.s3SecretKey | b64enc | quote }}
