apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "helm-chart.fullname" . }}
  labels:
    app: {{ template "helm-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: default
    options:
      name: default
      namespace: traefik
{{- if .Values.domains }}
    domains: 
{{ toYaml .Values.domains | indent 6 }}
{{- end }}
      
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name:  {{ template "helm-chart.fullname" . }}
      port: 5556
    middlewares:
    - name: sec-headers
      namespace: traefik


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "helm-chart.fullname" . }}-https-redirect
  labels:
    app: {{ template "helm-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name:  {{ template "helm-chart.fullname" . }}
      port: 5556
    middlewares:
    - name: redirect-https
      namespace: traefik
