apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 999
      initContainers:
        - name: copy-config
          image: supinf/envsubst
          command: ['/bin/sh']
          args:
            - '-c'
            - 'cat /tmp/murmur.ini | envsubst > /opt/murmur/config/murmur.ini'
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-mysql-auth
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-chart.fullname" . }}-mysql-auth
                  key: password
          volumeMounts:
            - name: murmur-config
              mountPath: /tmp/murmur.ini
              subPath: murmur.ini
            - name: config-dir
              mountPath: /opt/murmur/config
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 64738
              hostPort: 64738
              protocol: TCP
            - name: udp
              containerPort: 64738
              hostPort: 64738
              protocol: UDP
          volumeMounts:
            - name: config-dir
              mountPath: /opt/murmur/config
            - name: murmur-config
              mountPath: /opt/docker-entrypoint.sh
              subPath: docker-entrypoint.sh
            - name: ssl-config
              mountPath: /opt/murmur/cert
          command: ['/opt/docker-entrypoint.sh']
          args: ['murmur']
      volumes:
        - name: murmur-config
          configMap:
            name: {{ include "helm-chart.fullname" . }}-config
            defaultMode: 0777
        - name: ssl-config
          secret:
            secretName: {{ include "helm-chart.fullname" . }}-ssl
        - name: config-dir
          emptyDir: {}
