apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: luzifer/mumble:latest
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 64738
              hostPort: 64738
              protocol: TCP
            - name: udp
              containerPort: 64738
              hostPort: 64738
              protocol: UDP
          volumeMounts:
            - name: "mumble-server-config"
              mountPath: "/config/mumble-server.ini"
              subPath: "mumble-server.ini"
            - name: data
              mountPath: "/data/"
      volumes:
        - name: "mumble-server-config"
          configMap:
            name: {{ include "helm-chart.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}-pvc
