apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "cilium-portmap.name" . }}
  labels:
    app: {{ template "cilium-portmap.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "cilium-portmap.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "cilium-portmap.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: cilium-portmap
        image: snormore/cilium-portmap:latest
        volumeMounts:
          - name: host-etc-cni-netd
            mountPath: /host_etc_cni_netd
      volumes:
        - name: host-etc-cni-netd
          hostPath:
            path: /etc/cni/net.d
