apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "auth-proxy.fullname" . }}
  labels:
    app: {{ template "auth-proxy.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "auth-proxy.fullname" . }}
          servicePort: auth-proxy
