apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  RESTIC_PASSWORD: {{ required "restic password is required" .Values.password | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ required "s3AccessId user is required" .Values.s3AccessId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "s3SecretKey user is required" .Values.s3SecretKey | b64enc | quote }}
