apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "helm-chart.fullname" . }}
spec:
  endpoints:
  - port: metrics
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: ^traefik_.+
        action: keep
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
      release: {{ .Release.Name }}
