apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-h5bp-configs
  labels:
    app: {{ include "helm-chart.name" . }}
    chart: {{ include "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server_software_information.conf: |
    server_tokens off;

  media_types.conf: |
    include h5bp/mime.types;
    default_type application/octet-stream;

  character_encodings.conf: |
    charset utf-8;
    charset_types
        text/css
        text/plain
        text/vnd.wap.wml
        text/javascript
        text/markdown
        text/calendar
        text/x-component
        text/vcard
        text/cache-manifest
        text/vtt
        application/json
        application/manifest+json;

  compression.conf: |
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;

    gzip_types
      application/atom+xml
      application/geo+json
      application/javascript
      application/json
      application/ld+json
      application/manifest+json
      application/rdf+xml
      application/rss+xml
      application/vnd.ms-fontobject
      application/wasm
      application/x-web-app-manifest+json
      application/xhtml+xml
      application/xml
      font/otf
      image/bmp
      image/svg+xml
      text/cache-manifest
      text/calendar
      text/css
      text/javascript
      text/markdown
      text/plain
      text/vcard
      text/vnd.rim.location.xloc
      text/vtt
      text/x-component
      text/x-cross-domain-policy;


  # pre-compressed_content_brotli.conf: |
  #   brotli_static on;


  pre-compressed_content_gzip.conf: |
    gzip_static on;


  cache_expiration.conf: |
    map $sent_http_content_type $expires {
      default                                 1M;
      ""                                      off;
      ~*text/css                              1y;
      ~*application/atom\+xml                 1h;
      ~*application/rdf\+xml                  1h;
      ~*application/rss\+xml                  1h;
      ~*application/json                      0;
      ~*application/ld\+json                  0;
      ~*application/schema\+json              0;
      ~*application/geo\+json                 0;
      ~*application/xml                       0;
      ~*text/calendar                         0;
      ~*text/xml                              0;
      ~*image/vnd.microsoft.icon              1w;
      ~*image/x-icon                          1w;
      ~*text/html                             0;
      ~*application/javascript                1y;
      ~*application/x-javascript              1y;
      ~*text/javascript                       1y;
      ~*application/manifest\+json            1w;
      ~*application/x-web-app-manifest\+json  0;
      ~*text/cache-manifest                   0;
      ~*text/markdown                         0;
      ~*audio/                                1M;
      ~*image/                                1M;
      ~*video/                                1M;
      ~*application/wasm                      1y;
      ~*font/                                 1M;
      ~*application/vnd.ms-fontobject         1M;
      ~*application/x-font-ttf                1M;
      ~*application/x-font-woff               1M;
      ~*application/font-woff                 1M;
      ~*application/font-woff2                1M;
      ~*text/x-cross-domain-policy            1w;
    }
    expires $expires;


  content-security-policy.conf: |
    add_header Content-Security-Policy $content_security_policy always;


  x-ua-compatible.conf: |
    add_header X-UA-Compatible $x_ua_compatible;


  mime.types: |
    types {
      # Data interchange
        application/atom+xml                  atom;
        application/json                      json map topojson;
        application/ld+json                   jsonld;
        application/rss+xml                   rss;
        application/geo+json                  geojson;
        application/xml                       xml;
        application/rdf+xml                   rdf;
      # JavaScript
        text/javascript                       js mjs;
        application/wasm                      wasm;
      # Manifest files
        application/manifest+json             webmanifest;
        application/x-web-app-manifest+json   webapp;
        text/cache-manifest                   appcache;
      # Media files
        audio/midi                            mid midi kar;
        audio/mp4                             aac f4a f4b m4a;
        audio/mpeg                            mp3;
        audio/ogg                             oga ogg opus;
        audio/x-realaudio                     ra;
        audio/x-wav                           wav;
        audio/x-matroska                      mka;
        image/bmp                             bmp;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        image/jxr                             jxr hdp wdp;
        image/png                             png;
        image/svg+xml                         svg svgz;
        image/tiff                            tif tiff;
        image/vnd.wap.wbmp                    wbmp;
        image/webp                            webp;
        image/x-jng                           jng;
        video/3gpp                            3gp 3gpp;
        video/mp4                             f4p f4v m4v mp4;
        video/mpeg                            mpeg mpg;
        video/ogg                             ogv;
        video/quicktime                       mov;
        video/webm                            webm;
        video/x-flv                           flv;
        video/x-mng                           mng;
        video/x-ms-asf                        asf asx;
        video/x-ms-wmv                        wmv;
        video/x-msvideo                       avi;
        video/x-matroska                      mkv mk3d;
        image/x-icon                          cur ico;
      # Microsoft Office
        application/msword                                                         doc;
        application/vnd.ms-excel                                                   xls;
        application/vnd.ms-powerpoint                                              ppt;
        application/vnd.openxmlformats-officedocument.wordprocessingml.document    docx;
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet          xlsx;
        application/vnd.openxmlformats-officedocument.presentationml.presentation  pptx;
      # Web fonts
        font/woff                             woff;
        font/woff2                            woff2;
        application/vnd.ms-fontobject         eot;
        font/ttf                              ttf;
        font/collection                       ttc;
        font/otf                              otf;
      # Other
        application/java-archive              ear jar war;
        application/mac-binhex40              hqx;
        application/octet-stream              bin deb dll dmg exe img iso msi msm msp safariextz;
        application/pdf                       pdf;
        application/postscript                ai eps ps;
        application/rtf                       rtf;
        application/vnd.google-earth.kml+xml  kml;
        application/vnd.google-earth.kmz      kmz;
        application/vnd.wap.wmlc              wmlc;
        application/x-7z-compressed           7z;
        application/x-bb-appworld             bbaw;
        application/x-bittorrent              torrent;
        application/x-chrome-extension        crx;
        application/x-cocoa                   cco;
        application/x-java-archive-diff       jardiff;
        application/x-java-jnlp-file          jnlp;
        application/x-makeself                run;
        application/x-opera-extension         oex;
        application/x-perl                    pl pm;
        application/x-pilot                   pdb prc;
        application/x-rar-compressed          rar;
        application/x-redhat-package-manager  rpm;
        application/x-sea                     sea;
        application/x-shockwave-flash         swf;
        application/x-stuffit                 sit;
        application/x-tcl                     tcl tk;
        application/x-x509-ca-cert            crt der pem;
        application/x-xpinstall               xpi;
        application/xhtml+xml                 xhtml;
        application/xslt+xml                  xsl;
        application/zip                       zip;
        text/calendar                         ics;
        text/css                              css;
        text/csv                              csv;
        text/html                             htm html shtml;
        text/markdown                         md markdown;
        text/mathml                           mml;
        text/plain                            txt;
        text/vcard                            vcard vcf;
        text/vnd.rim.location.xloc            xloc;
        text/vnd.sun.j2me.app-descriptor      jad;
        text/vnd.wap.wml                      wml;
        text/vtt                              vtt;
        text/x-component                      htc;
    }
