dependencies:
- name: common
  version: 0.0.5
  repository: "file://../common"
- name: ingress
  alias: api-ingress
  version: "0.0.1"
  repository: "file://../ingress"
- name: nginx
  version: "0.1.0"
  repository: "file://../nginx"
